public with sharing class HelloWorld {

//--------------------------------------------------------------------------------------------
    // For each jobApp, create a chatter subscription for the hiring manager of the associated position
    // jobApps - the job applications to which the hiring managers should be subscribed.
    //--------------------------------------------------------------------------------------------
    public static String getMessage(){
        return 'Hellow World';
    }
}